development:
  :concurrency: 3
production:
  :concurrency: 3
:queues:
  - ['crawl_yahoo_auction_sync_products_enqueue_sync_job', 1]
  - ['crawl_yahoo_auction_sync_products_sync_job', 1]
  - ['crawl_yahoo_fleamarket_sync_products_enqueue_sync_job', 1]
  - ['crawl_yahoo_fleamarket_sync_products_sync_job', 1]
  - ['crawl_mercari_sync_products_enqueue_sync_job', 1]
  - ['crawl_mercari_sync_products_sync_job', 1]
  - ['crawl_janpara_enqueue_sync_job', 1]
  - ['crawl_janpara_sync_job', 1]
  - ['crawl_iosys_enqueue_sync_job', 1]
  - ['crawl_iosys_sync_job', 1]
  - ['crawl_pc_koubou_enqueue_sync_job', 1]
  - ['crawl_pc_koubou_sync_job', 1]
