development:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - ['crawl_yahoo_auction_sync_product_sync_job', 1]
  - ['crawl_yahoo_fleamarket_sync_product_sync_job', 1]
  - ['crawl_mercari_sync_product_sync_job', 1]
