Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Layout/IndentationStyle:
  Enabled: false
