crawl_yahoo_auction_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::YahooAuction::EnqueueSyncJob"
crawl_mercari_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::Mercari::SyncProducts::EnqueueSyncJob"
crawl_mercari_sync_bought_date_job:
  cron: "0 * * * *"
  class: "Crawl::Mercari::SyncBoughtDateJob"
analysis_yahoo_auction_enqueue_calculate_price_job:
  cron: "0 0 * * *"
  class: "Analysis::YahooAuction::EnqueueCalculatePriceJob"
