crawl_yahoo_auction_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::YahooAuction::EnqueueSyncJob"
crawl_mercari_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::Mercari::SyncProducts::EnqueueSyncJob"
products_calculate_daily_purchase_summary_calculator_job:
  cron: "0 0 * * *"
  class: "Products::CalculateDailyPurchaseSummary::CalculatorJob"
products_refresh_related_product_enqueue_refresh_job:
  cron: "0 * * * *"
  class: "Products::RefreshRelatedProduct::EnqueueRefreshJob"
