crawl_yahoo_auction_sync_products_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::YahooAuction::SyncProducts::EnqueueSyncJob"
crawl_yahoo_fleamarket_sync_products_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::YahooFleamarket::SyncProducts::EnqueueSyncJob"
crawl_mercari_sync_products_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::Mercari::SyncProducts::EnqueueSyncJob"
crawl_janpara_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::Janpara::EnqueueSyncJob"
crawl_iosys_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::Iosys::EnqueueSyncJob"
crawl_pc_koubou_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::PcKoubou::EnqueueSyncJob"
products_calculate_daily_purchase_summary_calculator_job:
  cron: "0 0 * * *"
  class: "Products::CalculateDailyPurchaseSummary::CalculatorJob"
