crawl_yahoo_auction_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::YahooAuction::EnqueueSyncJob"
crawl_mercari_enqueue_sync_job:
  cron: "*/20 * * * *"
  class: "Crawl::Mercari::SyncProducts::EnqueueSyncJob"
crawl_mercari_sync_bought_date_job:
  cron: "0 * * * *"
  class: "Crawl::Mercari::SyncBoughtDateJob"
analysis_calculate_yahoo_auction_daily_purchase_summary_job:
  cron: "0 0 * * *"
  class: "Analysis::CalculateYahooAuctionDailyPurchaseSummaryJob"
analysis_calculate_mercari_daily_purchase_summary_job:
  cron: "0 0 * * *"
  class: "Analysis::CalculateMercariDailyPurchaseSummaryJob"
products_enqueue_refresh_product_job:
  cron: "0 * * * *"
  class: "Products::EnqueueRefreshProductJob"
