crawl_yahoo_auction_crawl_job:
  cron: "*/10 * * * *"
  class: "Crawl::YahooAuction::EnqueueCrawlJob"
  queue: default
crawl_yahoo_auction_sync_job:
  cron: "*/10 * * * *"
  class: "Crawl::YahooAuction::EnqueueSyncJob"
  queue: default
