name: CI

on:
  push:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check for Backend Changes
        id: backend_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/' || echo 'no-backend-changes' > backend_changes.log
